#!/bin/bash

echo "running yamllint against repository"
yamllint .

echo "running golangci-lint against repository"
# a bit of bash trickery to silence the output on success
lint="$(golangci-lint run)"

if [[ $? -ne 0 ]] ; then
    echo "$lint"
fi

echo "running hadolint against Dockerfile"
hadolint Dockerfile

echo "running go test ./..."
# a bit of bash trickery to silence the output on success
test="$(go test ./...)"

if [[ $? -ne 0 ]] ; then
    echo "$test"
fi

