---
version: "3.3"

services:
  main:
    build: .
    environment:
      LKAPI_TITLE: "Letterkenny API"
      LKAPI_TEMPLATES_HOME: "/templates/home.gotmpl"
      LKAPI_PRODUCTIONURL: "http://localhost:8080"
    ports:
      - "8080:8080"
      - "8081:8081"
    
