package quotes

import "math/rand"

var LetterkennyQuotes = []string{
	"Fuck you, your life's so fuckin' miserable I ran a 15k to raise awareness for it",
	"Get this guy a fucking puppers.",
	"Dirty fuckin' dangles, boys!",
	"Fuck Lemony Snicket, what a series of unfortunate events you fuckin' been through you ugly fuck",
	"You don't fuck with tradition!",
	"Fuck you Shoresy!",
	"I made your mum so wet, Trudeau deployed a 24-hour infantry unit to stack sand bags around my bed!",
	"Pull out the gun, safety's off, fuckin' safety off boys.",
	"Allegedly...",
	"Pitter-patter, lets get at 'er.",
	"You're asking the important questions and that's what I appreciates about you.",
	"Big city slams, boys!",
	"Big city snipes, boys!",
	"Silk mittens, top tittens!",
	"Fore check, back check, pay check, boys!",
	"Ferda.",
	"If you've got a problem with her, then you've got a problem with me! And I suggest you let that one marinate!",
	"More hands make less work.",
	"Hard no.",
	"End of the laneway. Don't come up the property.",
	"That's a Texas-sized 10-4, good buddy!",
	"Great fishin' in Quebec",
	"Dial that back superchief.",
	"Always bardownski!",
	"Can confirm.",
	"Back to chorin'.",
	"I guess we gots to calls up the internet.",
	"It's impolite to kiss and tell.",
	"Three things, I hit you, you hit the pavement, ambulance hits 60.",
	"We'll see what you're calling us after I bury a couple of bar-down wristers.",
	"Half-clapper top-cheddar, biscuits top-titties bardownski, always bardownski.",
	"A little 3-on-1-ski, a little 3-on-2-ski, home a high hard one? Hit the red light district.",
	"Tim's, McDonald's, and the beer store are all closed on Christmas Day. And that's your whole world right there.",
	"Nice onesie. Does it come in men's?",
	"You'd best be preparin' for a donnybrook if you think I'm going to that super soft birthday party of yours.",
	"We need backup, boys.",
	"Oh, get off the cross, we need the wood.",
	"Where's the sacrifice?",
	"You're spare parts, aren't you, bud?",
	"That was well brought up. Too bad you weren't.",
	"Figure it out!",
	"It's a hard life picking stones and pullin' teats, but as sure as God's got sandals, it beats fightin' dudes with treasure trails.",
	"I wish you weren't so fucking awkward, bud.",
	"Buddy you couldn't wheel a fuckin' tire down a hill.",
	"What's up with your body hair, big shoots? You look like a 12-year-old Dutch girl.",
	"Crossfit? You can cross fuck off.",
	"Fuck you, Shoresy, you're a terrible fuckin' ref!",
	"Fuck you Jonesy! Your mom just liked my Instagram post from 2 years ago in Puerto Vallarta. Tell her I'll put my swim trunks on for her any time she likes.",
	"It's like algebra… Why you gotta put numbers and letters together?",
	"Fuck you, Jonesy, your life is so pathetic I get a charity tax break just by hanging around you!",
	"Tim's, McDonald's, and the beer store are all closed on Christmas Day. And that's your whole world right there.",
	"See the muscle shirt came today. Muscles coming tomorrow?",
	"Tell your mom to top off the cell phone she bought me so I can FaceTime her late night!",
	"Got anymore of that electric lettuce? These darts aren't doing it.",
	"Legen-Dary.",
	"Not my pig, not my farm.",
	"You're 10-Ply, Bud.",
	"In the words of the genre-bending Canadian indie rock band Arcade Fire, 'wake up.'",
	"Distribute some free literature.",
	"Sushis and sashimis.",
	"Strt!",
	"Bonnie McMurray!",
	"Wheel snipe celly!",
	"Tarps off boys!",
	"Certified beautician.",
	"You lookin' for a tilly buddy, lets have a donnybrook!",
	"You're a fuckin hero two two!",
}

func GetRandomQuote() string {
	return LetterkennyQuotes[rand.Intn(len(LetterkennyQuotes))]
}
